### ISSUE TITLE
Doesn't show sort properties

### ISSUE THREAD

**Issue by jfrumar** [mrsarm/mongotail#18]
This is a great tool. Unfortunately I'm trying to inspect my sort criteria, but it's not being displayed alongside the query.

Could I request to display the sort criteria too?

Thanks for this!

**Comment by mrsarm** [comment]
Hello @jfrumar . The problem was that old versions of MongoDB don't log the sort criteria parameters in the profiler (where Mongotail pull the log information). But now I tried again with the latest versions and this information is logged since MongoDB 3.2 !

So I will add this new feature in the next release of Mongotail, but it will only available for dbs running at least that version, databases with version equal or less than 3.0 are not compatible.

**Comment by jfrumar** [comment]
Sounds great - I confirmed that the sort values are present in our system.profile collection. Look forwards!

**Comment by mrsarm** [comment]
Released in version 2.1.0
