### ISSUE TITLE
ImportError: cannot import name string_type

### ISSUE THREAD

**Issue by zishiguo** [mrsarm/mongotail#22]
who know reason ?
![image](https://user-images.githubusercontent.com/13025675/29665673-bcb9351c-8907-11e7-877e-6f04bc973b58.png)

**Comment by mrsarm** [comment]
I think this is your problem: https://github.com/py-bson/bson/issues/29

Try to install in a virtualenv mongotail to see what happens.

Another thing you can do is install and execute mongotail with Python 3 instead of Python 2, so if you don't have installed the `bson` library in Python 3, there will be no conflicts. You ca achieve this with: ``sudo pip3 install mongotail``.

Let me know whether this worked for you or not.

**Comment by zishiguo** [comment]
@mrsarm thanks, refer to https://stackoverflow.com/questions/32618686/how-to-install-pip-in-centos-7
it has solved!
