### ISSUE TITLE
Supposed to work with Mongo 4.0.1?

### ISSUE THREAD

**Issue by borice** [mrsarm/mongotail#28]
OSX. MongoDB server version: 4.0.1
mongotail 2.2.0 <https://github.com/mrsarm/mongotail> (python 2.7.15)

`$ mongotail localhost/mydb --level 2 -f`
Profiling level set to level 2

then exits back to shell.

I should say that:
`$ mongotail localhost/mydb -f`
works fine, except doesn't show all the queries.

**Comment by mrsarm** [comment]
Hi @borice,

Yes, I tested mongotail with the first RC of Mongo 4.0 time ago, should works with the final releases.

I think the problem is that the -f options is overridden the --level option, because the command doesn't work well when you pass more than one option, try to remove the -f options on the first sentence.

Otherwise try just in case with the -v option in the second sentence.
